N = 64;
CP = 16;
numSym = 5;
bits = randi([0 1], N*2*numSym, 1);
bits_reshape = reshape(bits, 2, []).';
symbols = (1 - 2*bits_reshape(:,1)) + 1j*(1 - 2*bits_reshape(:,2));
symbols = symbols / sqrt(2);
ofdm_symbols = reshape(symbols, N, numSym).';
time_domain = ifft(ofdm_symbols, N, 2);
ofdm_with_cp = [time_domain(:, end-CP+1:end) time_domain];
received = ofdm_with_cp;
received_no_cp = received(:, CP+1:end);
received_symbols = fft(received_no_cp, N, 2);
received_symbols = received_symbols.';
received_bits = zeros(length(bits), 1);
received_bits(1:2:end) = real(received_symbols(:)) < 0;
received_bits(2:2:end) = imag(received_symbols(:)) < 0;
numErrors = sum(bits ~= received_bits);
BER = numErrors / length(bits);
fprintf('Bit errors: %d\nBit error rate: %f\n', numErrors, BER);
symbol_idx = 1;
figure;
stem(0:N-1, abs(ofdm_symbols(symbol_idx, :)));
title('OFDM Symbol in Frequency Domain (Magnitude)');
xlabel('Subcarrier Index');
ylabel('Magnitude');
grid on;
figure;
plot(real(ofdm_with_cp(symbol_idx, :)));
title('OFDM Symbol in Time Domain (Real Part)');
xlabel('Sample Index');
ylabel('Amplitude');
grid on
